include:
  # Default CI configuration
  - local: default.yml

  # Include optional branch-specific CI configuration
  - local: ${CI_COMMIT_REF_SLUG}.yml
    rules:
      - exists:
        - ${CI_COMMIT_REF_SLUG}.yml
